spring:
  profiles:
    active: db
  web:
    resources:
      static-locations: classpath:/static/, file:images/

server:
  servlet:
    context-path: /home

jwt:
  secret: MzJieXRlc2xvbmdzZWNyZXRrZXltb3JldGhhbmMzMmJ5dGVz
  duration: 3600000000

file:
  upload-dir: images
