spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://dpg-d22en063jp1c738r5dog-a.oregon-postgres.render.com:5432/postgres_test_tztk
##    postgresql: //root:a5yXoiwbsfCiH8XAltuCx4gIOabrjCC3@dpg-d22en063jp1c738r5dog-a.oregon-postgres.render.com/postgres_test_tztk
#    username: root
#    password: a5yXoiwbsfCiH8XAltuCx4gIOabrjCC3
#    driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate:
        format_sql= true:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.yml
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK